### ISSUE TITLE
Issue with member role add and remove

### ISSUE THREAD

**Issue by ITheEqualizer** [dbm-network/events#15]
Hello there

So it seems the event doesn't store the variables you enter at all.
https://i.imgur.com/Bz4xYPW.png
https://i.imgur.com/yaooyfU.png
https://i.imgur.com/bnTwZXo.png
https://i.imgur.com/jyEphXE.png

**Comment by LeonZ2019** [comment]
The event activate when role change so it is not bug from event and the undefined is mean list is not exist, it should be come from store member info

**Comment by ITheEqualizer** [comment]
> The event activate when role change so it is bug from event and the undefined is mean list is not exist, it should be come from store member info

So can you guys fix it? Since as you mentioned the event has some issues

**Comment by Mindlesscargo** [comment]
Have you tried seeing if the member is stored correctly, other than using store member info (such as sending the message and seeing if it mentions the user).

Edit: Made a pull request to fix. I made these a while ago and apparently didn't store the member object for some reason.
