### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by noamstar2** [dbm-network/events#34]
It doesn't store me the temp variables of the events idk what to do 

![image](https://user-images.githubusercontent.com/44677584/88459173-f8582380-ce9b-11ea-8980-25f7cb7c7b6d.png)

**Comment by NoahAlma** [comment]
It does. Just use the template at write test in it.

**Comment by noamstar2** [comment]
i don't understand

**Comment by NoahAlma** [comment]
You've stored the variable as `test` so write `${tempVars("test")}`. Not everything is done for you

**Comment by noamstar2** [comment]
i tried that.

**Comment by noamstar2** [comment]
if i remove the variable it sends in the chat the message. and yes i regenerated new invites. 
![image](https://user-images.githubusercontent.com/44677584/88461025-360f7900-cea9-11ea-8686-d8419db27667.png)

**Comment by noamstar2** [comment]
oh it works now
